# **NumPy Indexing and Selection**

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr=np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Bracket Indexing and Selection**

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr[8]

8

In [ ]:
# Negative indexing works like in python lists
arr[-1]

10

In [ ]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
# arr[start:stop:step], odds
arr[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
# arr[start:stop:step], evens
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

# Indexing a 2D array (matrices)

The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]       #Indexing row

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value

arr_2d[1][2]

30

In [ ]:
arr_2d[2,1]

40

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# 2D array slicing
#[row,col]

arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
arr_2d[:,1]

array([10, 25, 40])

In [ ]:
# convert 25 to 99

arr_2d[1,1]=99
arr_2d

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [ ]:
# default dtype is int.look at the assigning of the float value.Not work

arr_2d[1][1]=7.7
arr_2d

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

**Fancy Indexing**

Fancy indexing allows you to select entire rows or columns out of order.

In [ ]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
v[1]

3

In [ ]:
v[7]

21

In [ ]:
# we can select separate elements using their indices in a list
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [ ]:
v[[1,3,7]]

array([ 3,  9, 21])

In [ ]:
# Set up matrix
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
length_arr = arr2d.shape[0]
length_arr

10

In [ ]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Set up array
for i in range(length_arr):
    arr2d[i]=i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
# we can select separate rows by indices in a list
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

**any_array[[row , indices], [column , indices]]**

In [ ]:
jj=np.arange(1,17).reshape(4,4)

In [ ]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# select separate values of 5 and 12
# row 1 and column 0. row 2 and column 3. 
jj[[1,2],[0,3]]

array([ 5, 12])

In [ ]:
# this time let's select separate values of 1, 10 and 16
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

**Using basic index and fancy index together**

In [ ]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
jj[1,[1,3]]

array([6, 8])

In [ ]:
jj[[0,3],[1]]

array([ 2, 14])

**Using basic slicing and fancy index together**

In [ ]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
jj[1:3,[1,2]]  

array([[ 6,  7],
       [10, 11]])

In [ ]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

# **Selection on a Condition**

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
boolarr=arr>4

In [ ]:
arr[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [ ]:
# and ==> &                    # if you want you can use if_statement and for_loop
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

# **Broadcasting**
Numpy arrays differ from a normal Python list because of their ability to broadcast.

In [ ]:
#Setting a value with index range (Broadcasting)

arr[:5]=77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [ ]:
a=[0,2,4,6,8,10]

In [ ]:
a[:3]=[100,100,100]

In [ ]:
a

[100, 100, 100, 6, 8, 10]

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr    # effected original array because assinged a value on slice.COPY THE ORIGINAL DATA

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
# We can assign a list of values in an exact dimension
arr_copy[:6]=[0,1,2,3,4,5]

In [ ]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# **Arithmetic Operations**

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr    # Also warning, but not an error instead infinity

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v-2

array([-1,  0,  1,  2,  3])

In [ ]:
v*10

array([10, 20, 30, 40, 50])

In [ ]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)   # same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.sin(np.pi/2)

1.0

In [ ]:
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
v

array([1, 2, 3, 4, 5])

In [ ]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [ ]:
x1=np.arange(9.0).reshape(3,3)
x2=np.arange(3.0)

In [ ]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2

array([0., 1., 2.])

In [ ]:
x1-x2   #np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [ ]:
np.add(v,2)

array([3, 4, 5, 6, 7])

In [ ]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [ ]:
v

array([1, 2, 3, 4, 5])

In [ ]:
v**2

array([ 1,  4,  9, 16, 25])

In [ ]:
# v % 2
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [ ]:
np.absolute(np.array([-9,-80,9]))

array([ 9, 80,  9])

# **Statistical Calculations**

np.mean(arr,axis=0) | Returns mean along specific axis

arr.sum() | Returns sum of arr

arr.min() | Returns minimum value of arr

arr.max(axis=0) | Returns maximum value of specific axis

np.var(arr) | Returns the variance of array

np.std(arr,axis=1) | Returns the standard deviation of specific axis

np.corrcoef(arr) | Returns correlation coefficient of array

In [ ]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [ ]:
v.mean()

2.142857142857143

In [ ]:
np.median(v)

2.0

In [ ]:
v.std()

0.8329931278350429

In [ ]:
v.var()

0.6938775510204082

In [ ]:
np.random.seed(42)
xarr=np.random.randn(3,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [ ]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])