# Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

**Using Lists**

In [ ]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

**Using arrays**

In [ ]:
arr

array([10, 20, 30])

In [ ]:
pd.Series(data=arr,index = labels)

a    10
b    20
c    30
dtype: int64

**Using Dictionaries**

In [ ]:
d                                #dictionary has already indexes 

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(d,index=['q','c','y'])  # if there is same index uses.if not return nan.

q     NaN
c    30.0
y     NaN
dtype: float64

**Using Scalar Value**

In [ ]:
pd.Series(data = "humeyra")

0    humeyra
dtype: object

In [ ]:
pd.Series(data = "humeyra",index = range(10,13))

10    humeyra
11    humeyra
12    humeyra
dtype: object

In [ ]:
pd.Series(data = 10, index= ['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

# **Data in a Series**

A pandas Series can hold a variety of object types

In [ ]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [ ]:
pd.Series(set)[0]([2,5,7,5,8,2])   #set takes unique values.

{2, 5, 7, 8}

In [ ]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
pd.Series([sum, print, len])[1]("a")

a


In [ ]:
pd.Series([sum, print, len])[2]("clarusway")

9

In [ ]:
mix_data = ['Aziz', 2, True]

In [ ]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [ ]:
ser.dtype

dtype('O')

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
type(ser[1])

int

In [ ]:
type(ser[0])

str

In [ ]:
arr = np.array(mix_data)    #array makes change the data types while series preserve
arr

array(['Aziz', '2', 'True'], dtype='<U21')

In [ ]:
type(arr[2])

numpy.str_


# **Basic Attributes of Series**

.dtype
.size
.ndim
.head
.tail
.shape
.sample

.sort_index()
.sort_values()
.isin
.index
.keys()
.values
.items()

In [ ]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    75
1    33
2    82
3    78
4    27
5    58
6    48
dtype: int64

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
ser.dtype

dtype('int64')

In [ ]:
ser.shape

(7,)

In [ ]:
ser.size

7

In [ ]:
len(ser)

7

In [ ]:
ser.ndim

1

In [ ]:
ser

0    75
1    33
2    82
3    78
4    27
5    58
6    48
dtype: int64

In [ ]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [42]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [43]:
ser.keys()   #keys is used for indexes

RangeIndex(start=0, stop=7, step=1)

In [44]:
ser.keys

<bound method Series.keys of 0    75
1    33
2    82
3    78
4    27
5    58
6    48
dtype: int64>

In [46]:
ser.values

array([75, 33, 82, 78, 27, 58, 48])

In [50]:
ser.items()

In [51]:
list(ser.items())

[(0, 75), (1, 33), (2, 82), (3, 78), (4, 27), (5, 58), (6, 48)]

In [52]:
for index,value in ser.items():
  print(f"index: {index},value: {value}")

index: 0,value: 75
index: 1,value: 33
index: 2,value: 82
index: 3,value: 78
index: 4,value: 27
index: 5,value: 58
index: 6,value: 48


In [53]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])

In [54]:
ser

c    18
b    24
a    11
e     9
f    19
d     4
g     0
i    10
h    13
j     0
dtype: int64

In [55]:
ser.head(3)

c    18
b    24
a    11
dtype: int64

In [56]:
ser.tail()

d     4
g     0
i    10
h    13
j     0
dtype: int64

In [58]:
ser.sample(2)   #random sample from data

a    11
c    18
dtype: int64

In [60]:
ser.sort_index(ascending =True)

a    11
b    24
c    18
d     4
e     9
f    19
g     0
h    13
i    10
j     0
dtype: int64

In [61]:
ser.sort_values(ascending=False)

b    24
f    19
c    18
h    13
a    11
i    10
e     9
d     4
g     0
j     0
dtype: int64

In [62]:
ser    #sort doest change data permanently

c    18
b    24
a    11
e     9
f    19
d     4
g     0
i    10
h    13
j     0
dtype: int64

In [63]:
ser.isin([5,9])

c    False
b    False
a    False
e     True
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [65]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [66]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

# **Indexing Pandas Series**


In [67]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                      

In [68]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [69]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [70]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [71]:
ser1[1]

2

In [72]:
ser1['Germany']

2

In [73]:
ser1.Germany    #for string data(without blank) only

2

In [74]:
ser1+ser2       #add values of same indexes

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [75]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])

ser3

0    a
1    b
2    c
3    d
dtype: object

In [76]:
ser3[0]

'a'

In [77]:
ser3[2:]

2    c
3    d
dtype: object

In [78]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

**pandas_series[index] | pandas_series[[indices, indices...]]**


In [79]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [80]:
panser['terry'] 

121

In [81]:
panser[0]

121

In [87]:
panser[["terry","orion"]]  # return seperate wanted indexes

terry    121
orion    150
dtype: int64

In [88]:
panser["terry":"orion"]   #return indexes with slicing.Includes last.

terry      121
micheal    200
orion      150
dtype: int64

In [84]:
index1=["terry", "micheal", "jason"]  #list of wanted indexes

In [85]:
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [86]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

# **Recap for Several Selecting Attributes and Some New Attributes**

In [89]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [90]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [91]:
panser.values

array([121, 200, 150,  99])

In [92]:
panser.items()

In [93]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [94]:
for index, value in panser.items():
  print(index,value)
 

terry 121
micheal 200
orion 150
jason 99


In [95]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [96]:
"terry" in panser

True

In [97]:
"bob" in panser

False

In [99]:
121 in panser.values

True

In [102]:
a = panser.isin([200,150])
a

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [104]:
panser[a]

micheal    200
orion      150
dtype: int64

In [107]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [110]:
panser["terry"] = 90  #assign a value

In [111]:
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [112]:
panser[panser<100]

terry    90
jason    99
dtype: int64

In [113]:
panser[panser<100] = 100

In [114]:
panser

terry      100
micheal    200
orion      150
jason      100
dtype: int64

In [115]:
panser[panser>100]

micheal    200
orion      150
dtype: int64