___

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S02_(Numpy_Indexing_Selection_Operations).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S2_%28Numpy_Indexing_Selection_Operations%29/DAwPy_S2_%28Numpy_Indexing_Selection_Operations%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 02</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays - Part - 02</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CONCATENATION OF THE ARRAYS](#00)
    * [2D Matrix](#00.1)
* [SPLITTING OF THE ARRAYS](#000)
    * [2D Matrix](#000.1)
* [SORTING OF THE ARRAYS](#0000)
    * [2D Matrix](#0000.1)
* [NUMPY INDEXING & SELECTION](#1)
    * [Bracket Indexing & Selection](#1.1)
    * [Indexing a 2D Array (Matrices)](#1.2)
    * [Slicing a 2D Array (Matrices)](#1.3)
    * [Fancy Indexing](#1.4)
    * [Using Basic Index & Fancy Index Together](#1.5)
    * [Using Basic Slicing & Fancy Index Together](#1.6)
    * [More Indexing Help](#1.7)
* [SELECTION ON A CONDITION](#2)
* [BROADCASTING](#3)
* [NUMPY OPERATIONS](#4)
    * [Arithmetic Operations](#4.1)
    * [Universal Array Functions](#4.2)
    * [Statistical Calculations](#4.3)
* [OFFICIAL TUTORIAL](#5)
* [THE END OF THE SESSION-02](#6)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

**``NOTE:``** For installation instructions, please refer to the notebook at SESSION-01 (Numpy Part-01)

In [1]:
import pandas as pd

# import warnings
# warnings.filterwarnings("ignore")  # to suppress all warnings

**REMINDER**<br>
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

**Why do we need NumPy?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly (Remember the concept of "Vectorization" from our previous session). For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Concatenation of the Arrays</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this lecture we will first discuss how to concatenate, split and sort the arrays.

**``concatenate((a1, a2, ...), axis=0, out=None)``**

**Concatenation of two 1D `numpy` Arrays Along an Axis**

<img src="https://i.ibb.co/FYfgqz7/concat-of-1-Darray.png">

[Image Credit: Kanopi.org](https://kanoki.org/2020/01/10/concatenating-arrays-in-numpy/)

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [3]:
# ? np.concatenate
# help(np.concatenate)

In [4]:
np.concatenate([x, y])  # concatenates two or more one-dimensional arrays.

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6])

From the [NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html): The arrays you want to concatenate need **to be passed in as a sequence**, not as separate arguments.

In [5]:
np.concatenate([x, y, z], axis=0)  # The default axis value is 0. That is, in single dimensions, it combines along axis=0.

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# np.concatenate([x, y, z], axis=1) # gives an error

In [7]:
print(x.reshape(1, 3).shape)

np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis=0)

# This is how it works if the arrays are reshaped by reshape() method.

(1, 3)


<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# The second approach

np.concatenate([[x, y, z]], axis=0)
               
# By changing the number of square brackets for a one-dimensional array; 
# However, BE NOTED THAT we can combine along with only axis=0.               

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# The third approach

np.concatenate([x, y, z], axis=0).reshape(3, 3)

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# The fourth approach

print(x.shape)
print(x.reshape(1, 3).shape)
print(x.reshape(-1, 1).shape)

np.concatenate((x.reshape(-1, 1), y.reshape(-1, 1), z.reshape(-1, 1)), axis=1)

(3,)
(1, 3)
(3, 1)


<IPython.core.display.Javascript object>

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

You can also use **``stack()``** to join sequence of arrays. Just make sure both the 1D arrays are of the same shape.

In [11]:
# The fifth approach

print(x.shape)
print(y.shape)

np.stack([x, y]).reshape(-1)

(3,)
(3,)


<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6])

**``hstack()``** method Stack arrays in sequence horizontally, So if two 1D arrays are given then it flatten it to a single 1D

In [12]:
# The sixth approach

np.hstack([x, y])

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="00.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [13]:
a = np.random.randint(10, size=(2, 3))
b = np.random.randint(10, size=(2, 3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
a, b

(array([[8, 9, 5],
        [0, 4, 5]]),
 array([[7, 3, 5],
        [8, 0, 6]]))

In [15]:
# Combining two arrays of 2*3 on the basis of axis=0 results in an array of 4*3.

np.concatenate([a, b])

<IPython.core.display.Javascript object>

array([[8, 9, 5],
       [0, 4, 5],
       [7, 3, 5],
       [8, 0, 6]])

In [16]:
# Combining two arrays of 2*3 on the basis of axis=1 results in an array of 2*6.

np.concatenate([a, b], axis=1)

<IPython.core.display.Javascript object>

array([[8, 9, 5, 7, 3, 5],
       [0, 4, 5, 8, 0, 6]])

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(x.shape)
print(y.shape)

x, y

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(2, 3)
(3, 3)


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [18]:
# For example: When combining on the basis of axis=0, if the column numbers are equal, 
# it does the combination and does not give an error.

np.concatenate([x, y], axis=0)

<IPython.core.display.Javascript object>

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## 🔥 Be Noted 🔥

All the input array dimensions for the concatenation axis must match exactly

<img src="https://i.ibb.co/DCW2Mhr/concat-of-1-Darray1.png" alt="Numpy Concatenation">

<p><a href="https://kanoki.org/2020/01/10/concatenating-arrays-in-numpy/">Image Credit: Kanopi.org</a></p>

In [19]:
# np.concatenate([x, y], axis=1)  # Gives an error of "ValueError"

# # all the input array dimensions for the concatenation axis must match exactly

For more information, you can visit this article on **[Concatenating arrays in Numpy](https://kanoki.org/2020/01/10/concatenating-arrays-in-numpy/)**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Splitting of the Arrays</p>

<a id="000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``np.split(ary, indices_or_sections, axis=0)``**

In [20]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

<IPython.core.display.Javascript object>

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [21]:
# With the np.split() method, you can split an array into parts as you specify.

np.split(x, [3, 5])  # divided into 0:3, 3:5, 5:

<IPython.core.display.Javascript object>

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[3, 5]`` would, for ``axis=0``, result in
- ``ary[:3]``
- ``ary[3:5]``
- ``ary[5:]``

In [22]:
# We assigned the parts we divided as 0:3, 3:5, 5: to a new variable.

a, b, c = np.split(x, [3, 5])

<IPython.core.display.Javascript object>

In [23]:
a

array([1, 2, 3])

In [24]:
b

array([99, 99])

In [25]:
c

array([3, 2, 1])

In [26]:
np.split(x, [4])  # It divided the array into two parts as 0:4, 4:  

<IPython.core.display.Javascript object>

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [27]:
np.split(x, 4)

# If we do not give the index number in square brackets, it will divide it into 4 equal parts.
# However, in this case, the number of elements in the array must be a number divisible by 4.

<IPython.core.display.Javascript object>

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [28]:
# x = np.array([1, 2, 3, 99, 99, 3, 2, 1, 4])  # the length of array is 9
# np.split(x, 4)

# # ValueError: array split does not result in an equal division

The number of the elements ``should be divisible`` by 4, otherwise raises an error. If the argument (here is 4) is **not enclosed by square brackets**, then it means **dividing into equal 4 pieces.**

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [29]:
m = np.arange(20).reshape(5, 4)
m

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
np.split(m, 5, axis=0)  # axis=0 ==> we divided it into 5 equal parts along the rows. 

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [31]:
# When splitting two-dimensional arrays, the axis must be specified along with the indexes.

np.split(m, [1, 3], axis=0)  # axis=0 ==> we divided it into three parts as :1, 1:3:, 3:, along the rows.

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [32]:
np.split(m, [1, 3], axis=1)  # axis=1 ==> we divided it into three parts, :1, 1:3:, 3:, along the columns.

<IPython.core.display.Javascript object>

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [33]:
np.vsplit(m, [1, 3])  # With vertical split, we divided it into two parts as :3, 3: along the lines (like axis=0).

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [34]:
upper, lower = np.vsplit(m, [3])

<IPython.core.display.Javascript object>

In [35]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
# Focus on double square brackets. All rows are still 2d-arrays.

np.vsplit(m, 5)

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [38]:
np.hsplit(m, [2])  # With horizontal split, we divided it into two parts as :3, 3: along the columns (like axis=1).

<IPython.core.display.Javascript object>

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [39]:
left, right = np.hsplit(m, [2])

<IPython.core.display.Javascript object>

In [40]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [41]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Sorting of the Arrays</p>

<a id="0000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [42]:
v = np.array([2, 1, 4, 3, 5])
v

<IPython.core.display.Javascript object>

array([2, 1, 4, 3, 5])

In [43]:
np.sort(v)  # Returns a sorted array but does not change the original one.

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5])

In [44]:
v

array([2, 1, 4, 3, 5])

In [45]:
v.sort()  # changed inplace

# when used in this way, it makes this change both in the sequence (order) and in the original one.

In [46]:
v

array([1, 2, 3, 4, 5])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="0000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [47]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

<IPython.core.display.Javascript object>

array([[50, 48, 36],
       [22, 61, 62],
       [32, 79,  6]])

In [48]:
np.sort(twoD, axis=0)  # the rows are sorted from upper to lower and column by column

<IPython.core.display.Javascript object>

array([[22, 48,  6],
       [32, 61, 36],
       [50, 79, 62]])

In [49]:
np.sort(twoD, axis=1)  # the columns are sorted from left to right and row by row

<IPython.core.display.Javascript object>

array([[36, 48, 50],
       [22, 61, 62],
       [ 6, 32, 79]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this part of the lecture we will discuss how to select elements or groups of elements from an array.

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. [SOURCE](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp)

### ``Types of Indexing``

There are **``two types of indexing:``**

**``1 - Basic Slicing and indexing:``** Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
- a slice object that is of the form start : stop : step
- an integer
- or a tuple of slice objects and integers

**``2 - Advanced indexing:``** Advanced indexing is triggered when obj is –

- an ndarray of type integer or Boolean
- or a tuple with at least one sequence object
- is a non tuple sequence object

For more information, please visit [INDEXING SOURCE](https://www.geeksforgeeks.org/numpy-indexing/)


[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://numpy.org/doc/stable/reference/arrays.indexing.html),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://pandas.pydata.org/pandas-docs/version/1.2.4/user_guide/indexing.html),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=9nbBTaz2qXI) &
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

In [50]:
#Creating sample array

arr = np.arange(0, 11)

<IPython.core.display.Javascript object>

In [51]:
#Show

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Bracket Indexing & Selection</p>

<a id="1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [52]:
#Get a value at an index

arr[8]

8

In [53]:
# Negative indexing works like in python lists

arr[-1]

10

In [54]:
# Get values in a range

arr[1:5]  # Returns the elements in the index of 1 (inclusive)-5 (exclusive)

array([1, 2, 3, 4])

In [55]:
# Get values in a range

arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# arr[start:stop:step], odds

arr[1::2]

array([1, 3, 5, 7, 9])

In [58]:
# arr[start:stop:step], evens

arr[0::2]

# Returns the elements of the array corresponding to the even indexes starting from 0 with a step interval of 2

array([ 0,  2,  4,  6,  8, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Indexing a 2D Array (Matrices)</p>

<a id="1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row, col]</b>.<br> 
It's usually recommended using the comma notation for clarity.</p>

![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png)

[SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40msjahid%2Fnumpy-array-indexing-slicing-23b70abb8433&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAk), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fiq.opengenus.org%2F2d-array-in-numpy%2F&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAp)<br>

In [59]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

#Show
arr_2d

<IPython.core.display.Javascript object>

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [61]:
# Format is arr_2d[row][col] or arr_2d[row, col]

# Getting individual element value

arr_2d[1][2]

30

**While indexing two-dimensional arrays, first the row numbers are written to the left of the comma, and then the column numbers are written to the left of the comma.**

In [62]:
# Getting individual element value

arr_2d[1, 2]

30

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Slicing a 2D Array (Matrices)</p>

<a id="1.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you know how to select subsets of Python lists, you know most of what you need to know about ndarray slicing. The elements of the array being indexed that correspond to the elements of the indexing object are returned in a new array. The most important aspect of indexing is to remember that there is more than one dimension, and the indexing method should be able to handle these other dimensions.

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F16096753%2Fpython-array-slicing-how-can-2d-array-slicing-be-implemented&psig=AOvVaw0cHqeY-itYpRm19imsEBuR&ust=1644054927553000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCNiUt4vk5fUCFQAAAAAdAAAAABAD)

**When slicing two-dimensional arrays, first row and then column ranges should be written.**

In [64]:
# 2D array slicing
print(arr_2d)

# Shape (2, 2) from top right corner
arr_2d[0:2, 1:]

# Returns the rows from the beginning to the second index and the columns from the 1st to the end.

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [65]:
# Shape bottom row

arr_2d[2]  # Returns the elements in the 2nd index of row

array([35, 40, 45])

In [66]:
#Shape bottom row

arr_2d[2, :]  # Returns the row at the index of 2 with all columns

array([35, 40, 45])

In [67]:
# Middle column

arr_2d[:, 1]  # Returns the column at the index of 1 with all rows

array([10, 25, 40])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# The very right column

arr_2d[:, 2]

# When slicing two-dimensional arrays, first row and then column ranges should be written.

array([15, 30, 45])

In [70]:
# let's convert 25 to 55

arr_2d[1, 1] = 99
arr_2d

# In this way, we can permanently replace the values at the index we defined with another value.

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [71]:
# default dtype is int. take a look at the assigning of the float value

arr_2d[1][1] = 7.7
arr_2d

# When you assign a float value, it converts to int because the default value of the array is int.

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Fancy Indexing</p>

<a id="1.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once [SOURCE](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.). In Fancy Indexing, we pass array of indices instead of single scalar(numbers) to fetch elements at different index points. Remember that the shape of the output depends on the shape of the index arrays rather than the shape of the array being indexed. [SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftahamaddam.com%2Fcoding%2Fnumpy%2Fnumpy-fancy-indexing%2F&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAD), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F52485840%2Fnumpy-fancy-indexing-with-tuples%3Frq%3D1&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAO), [VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [72]:
v = np.arange(0, 30, 3)
v

<IPython.core.display.Javascript object>

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [73]:
v[1]

3

In [74]:
v[3]

9

In [75]:
v[7]

21

In [76]:
# we can select separate elements using their indices in a list

index_list=[1, 3, 7]

v[index_list]

array([ 3,  9, 21])

In [77]:
# Fancy indexing is used to select multiple values at different indices at the same time.

v[[1 ,3, 7]]  # Returns the values in index of 1, 3 and 5 in a one-dimensional array.

array([ 3,  9, 21])

In [78]:
# Set up matrix

arr2d = np.zeros((10, 10), dtype=int)
arr2d

<IPython.core.display.Javascript object>

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [79]:
arr2d.shape

(10, 10)

In [80]:
# Length of array

length_arr = arr2d.shape[0]
length_arr

10

In [81]:
arr2d[0]  # Returns the 1st row of the array named arr2d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
#Set up array

for i in range(length_arr):
    arr2d[i]=i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [84]:
arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Fancy indexing allows the following

In [85]:
# we can select separate rows by indices in a list

arr2d[[2, 4, 6, 8]]  # Returns the 2nd, 4th, 6th, and 8th rows of the array named arr2d in the order we defined.

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [86]:
# Allows in any order

arr2d[[6, 4, 2, 7]]  # Returns the 6th, 4th, 2nd, and 7th rows of the array named arr2d in the any order we defined.

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

<h3>any_array[[row indices], [column indices]]</h3>

In [87]:
jj = np.arange(1, 17).reshape(4, 4)

<IPython.core.display.Javascript object>

In [88]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**In two-dimensional arrays, point values can be reached by specifying row indexes and column indexes with the fancy index method.**

In [89]:
# let's select separate values of 5 and 12
# row 1 and column 0. row 2 and column 3. 

jj[[1, 2], [0, 3]]

array([ 5, 12])

In [90]:
# this time let's select separate values of 1, 10 and 16

jj[[0, 2, 3], [0, 1, 3]]  # the element 0 of row index 0, element 1 of row index 2, element 3 of row index 3

array([ 1, 10, 16])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Index*** & ***Fancy Index*** Together</p>

<a id="1.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>



In [91]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
# let's select 6 and 8 which are in the same row (index 1)

jj[1, [1, 3]]

array([6, 8])

In [93]:
# let's select 2 and 14 which are the same column (index 1)

jj[[0, 3], 1]

array([ 2, 14])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Slicing*** & ***Fancy Index*** Together</p>

<a id="1.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


**Sometimes basic index and fancy index method can be used together.**

In [94]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
# let's select two middle columns

jj[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
jj[1, [1, 3]]  # 1st element of row index 1, 3rd element of row index 1

array([6, 8])

In [97]:
# let's select center small square (4 elements)

jj[1:3, [1, 2]]

array([[ 6,  7],
       [10, 11]])

In [98]:
# remember, how normal slicing is executed

jj[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">More Indexing Help</p>

<a id="1.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fscipy-lectures.org%2Fintro%2Fnumpy%2Farray_object.html&psig=AOvVaw21eb1iMrmWndUhejWXLkY-&ust=1644056657663000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCICAqr_q5fUCFQAAAAAdAAAAABAD)

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views. [SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selection on a Condition</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [99]:
arr = np.arange(1, 11)
arr

<IPython.core.display.Javascript object>

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**When a condition is applied to an array, it is checked whether the elements of the array meet this condition one by one, and an array containing as many boolean values as the number of arrays is created.**

In [100]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
bool_arr = arr > 4

In [102]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
# When we write a condition in [] and write the name of the array next to it, 
# we get an array containing the elements that meet this condition.

arr[arr < 6]

array([1, 2, 3, 4, 5])

In [104]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# Sometimes it may be necessary to apply more than one condition.

(arr != 3) & (arr != 4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
# and ==> &

arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [107]:
# if you want you can use if_statement and for_loop

con_arr = []

for i in arr:
    if (i != 3) & (i != 4):
        con_arr.append(i)
print(con_arr)    

[1, 2, 5, 6, 7, 8, 9, 10]


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Broadcasting</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy arrays differ from a normal Python list because of their ability to broadcast [SOURCE](https://numpy.org/doc/stable/user/theory.broadcasting.html).<br>

**``Broadcasting``** is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size [SOURCE](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20is%20the%20name%20given,a%20different%20shape%20or%20size.&text=Subject%20to%20certain%20constraints%2C%20the,that%20they%20have%20compatible%20shapes.).<br>

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **``broadcast``** across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation [SOURCE](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).<br> 

Broadcasting is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays (eg per-element aritmetic) [SOURCE01](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73), [SOURCE02](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f).<br>

**NumPy Broadcasting Limitations**<br>
Broadcasting is a very easy and handy tool when working with Numpy arrays. Although, there are many rules and restrictions to perform the operations.

There are constraints on the dimension and shape of the arrays. We can perform broadcasting in cases where both the arrays have the same shape or only if either of the two has a size of 1. Also, we have to consider the dimensions in reverse order. We count it from the trailing dimension [SOURCE](https://data-flair.training/blogs/numpy-broadcasting/).<br>

Be informed about the discussion on [When broadcasting is a bad idea? (numpy)](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy) at Stackoverflow.

More Sources: [SOURCE01](https://inblog.in/Broadcasting-in-Numpy-A-Complete-Guide-jfKy2vzHiY), [SOURCE02](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), [SOURCE03](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), [SOURCE04](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), [SOURCE05](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), [SOURCE06](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), [SOURCE07](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), [SOURCE08](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)

In [108]:
# Let us remember our arr

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**We can take a specific part of the array and change its values.**

In [109]:
#Setting a value with index range (Broadcasting)
arr[:5] = 77

#Show
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [110]:
# What about broadcating on a Python list

a = [0, 2, 4, 6, 8, 10]
a

[0, 2, 4, 6, 8, 10]

In [111]:
# a[0:3] = 100 # gives an error of "TypeError: can only assign an iterable"

In [112]:
a[:3] = [100, 100, 100]

In [113]:
a

[100, 100, 100, 6, 8, 10]

In [114]:
# Let us reset our array, we'll see why we had to reset in  a moment
arr = np.arange(0, 11)

# Show
arr

<IPython.core.display.Javascript object>

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [116]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now **``note``** that the changes also occur in our original array!

In [117]:
arr  # The changes I copied from the array and made to the array also change the original array.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**To prevent this, we should work by making a copy of the array with the copy() function.**

Data is not copied, it's a view of the original array! This avoids memory problems!

In [118]:
#To get a copy, need to be explicit

arr_copy = arr.copy()
arr_copy

# If you make a copy of the array and operate on its copy, the changes you made in the original array will not take place.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [119]:
# We can assign a list of values in an exact dimension

arr_copy[:6] = [0, 1, 2, 3, 4, 5]

In [120]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/n65mpTL/numpy-operations.png)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Arithmetic Operations</p>

<a id="4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [122]:
import numpy as np

arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

An array can be added to another array. In this case, the shapes of the arrays must be compatible. It performs element-wise operation.

In [123]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

An array can be multiplied by another array.

In [124]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

An array can be subtracted from another array.

In [125]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
import warnings
warnings.filterwarnings('ignore')

In [127]:
# Warning on division by zero, but not an error!
# Just replaced with nan

arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [128]:
# Also warning, but not an error instead infinity

1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

You can get any power of an array.

In [129]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [130]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [131]:
v - 2

array([-1,  0,  1,  2,  3])

In [132]:
v * 10

array([10, 20, 30, 40, 50])

In [133]:
v*5 / 10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Universal Array Functions</p>

<a id="4.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/QYWBrtK/numpy-operations1.png)

[SOURCE01](https://medium.com/swlh/universal-functions-ufuncs-a-weapon-of-numpy-b8d0145a3808), 
[SOURCE02](https://www.brainstobytes.com/hands-on-numpy-universal-functions-and-array-oriented-programming/)




#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
#Taking Square Roots

# arr**0.5

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [136]:
#Calcualting exponential (e^)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [137]:
# same as arr.max()

np.max(arr)

9

In [138]:
# there are many trigonometric functions

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [139]:
np.sin(np.pi/2)

1.0

In [140]:
np.tan(np.pi/4)

0.9999999999999999

In [141]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [142]:
np.log10(1000)

3.0

In [143]:
v

array([1, 2, 3, 4, 5])

In [144]:
# v - 1

np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [145]:
x1=np.arange(9.0).reshape(3, 3)
x2=np.arange(3.0)

In [146]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [147]:
x2

array([0., 1., 2.])

In [148]:
# x1 - x2

np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [149]:
# v + 2

np.add(v, 2)

array([3, 4, 5, 6, 7])

In [150]:
# v / 2

np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [151]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [152]:
# v**2

np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [153]:
# v % 2

np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [154]:
np.absolute(np.array([-9]))

array([9])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Statistical Calculations</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Statistics is concerned with collecting and then analyzing that data. It includes methods for collecting the samples, describing the data, and then concluding that data. NumPy is the fundamental package for scientific calculations and hence goes hand-in-hand for NumPy statistical Functions.

NumPy contains various statistical functions that are used to perform statistical data analysis. These statistical functions are useful when finding a maximum or minimum of elements. It is also used to find basic statistical concepts like standard deviation, variance, etc.

NumPy is equipped with the following statistical functions:

**``np.amin(arr)``** This function determines the minimum value of the element along a specified axis.<br>
**``np.amax(arr)``** This function determines the maximum value of the element along a specified axis.<br>
**``arr.min()``** Returns minimum value of arr<br>
**``arr.max(axis=0)``** Returns maximum value of specific axis<br>
**``np.mean(arr, axis=0)``** It determines the mean value of the data set.<br>
**``np.median(arr)``** It determines the median value of the data set.<br>
**``np.std(arr, axis=1)``** It determines the standard deviation.<br>
**``np.var(arr)``** It determines the variance.<br>
**``np.ptp(arr)``** It returns a range of values (maximum - minimum) along an axis.<br>
**``np.average(arr)``** It determines the weighted average.<br>
**``np.percentile(arr)``** It determines the nth percentile of data along the specified axis.<br>
**``np.corrcoef(arr)``** Returns correlation coefficient of array

More Sources: [SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/), [SOURCE02](https://python-tricks.com/statistical-functions-in-numpy/), [SOURCE03](https://numpy.org/doc/stable/reference/routines.statistics.html), [SOURCE04](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), [SOURCE05](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), [SOURCE06](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), [SOURCE07](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE08](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE09](https://www.codecademy.com/learn/intro-statistics-numpy)

In [155]:
v = np.array([1, 1, 2, 2, 3, 3, 3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [156]:
np.ptp(v)  # The name of the function comes from the acronym for ‘peak to peak’. 
           # It's the range of values (maximum - minimum) along an axis.

# The term of Peak-to-peak is used in Electrical Engineering, and
# Peak-to-peak value is the maximum voltage change occurring during one cycle of alternating voltage or current.

2

In [157]:
print(np.mean(v))

v.mean()

2.142857142857143


2.142857142857143

In [158]:
print(np.median(v))

np.percentile(v, 50)

# v.median()  # This gives an error of "AttributeError: 'numpy.ndarray' object has no attribute 'median'"

2.0


2.0

In [159]:
from scipy import stats

stats.mode(v)

# np.mode(v)  # AttributeError: module 'numpy' has no attribute 'mode'

ModeResult(mode=array([3]), count=array([3]))

In [160]:
v.std()

0.8329931278350429

In [161]:
v.var()

0.6938775510204082

In [162]:
v.sum()

15

In [163]:
v.min()  # Returns min values along axis=0

1

In [164]:
np.random.seed(42)  # When you want to work with randomly generated values in individual or team work, 
                    # seed() method is used to reach the same values.

xarr = np.random.randn(3, 3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

**[The Story Behind Random.Seed(42) In Machine Learning](https://medium.com/geekculture/the-story-behind-random-seed-42-in-machine-learning-b838c4ac290a)**

In [165]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Official Tutorial</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session - 02</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" title="Open and Execute in Google Colaboratory"></a><br/>


## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>
___